// Pass each process only its runtime configuration. The proxy administration key
// and provider write credentials never belong in the local application launcher.
const systemKeys = new Set(['PATH','PATHEXT','SYSTEMROOT','WINDIR','COMSPEC','TEMP','TMP','HOME','USERPROFILE','APPDATA','LOCALAPPDATA','PROGRAMFILES','PROGRAMFILES(X86)','PROGRAMDATA','NUMBER_OF_PROCESSORS','PROCESSOR_ARCHITECTURE','LANG','LC_ALL','TERM','COLORTERM','NO_COLOR','FORCE_COLOR','NODE_ENV']);
const common = ['HOTL_MODE','NEXT_TELEMETRY_DISABLED'];
const allowed = {
  guardrails: ['HOTL_INTERNAL_TOKEN','GUARDRAIL_STATE_PATH','GUARDRAIL_DATABASE_URL','GUARDRAIL_WORKSPACE_ID','GUARDRAIL_INITIALIZE_EMPTY_DATABASE','GUARDRAIL_INITIALIZE_EMPTY_FILE','GUARDRAIL_AUTHORIZATION_VERSION','GUARDRAIL_TOKENS_VALID_AFTER','GUARDRAIL_REVOKED_TOKEN_IDS','GUARDRAIL_REVOKED_SESSION_IDS','KILL_SWITCH_URL','KILL_SWITCH_READ_TOKEN','SUPABASE_URL','OWNER_USER_IDS','OWNER_USER_ID','SUPABASE_OWNER_IDS','AGENT_JWT_SECRET','AGENT_JWT_KEYS','AGENT_JWT_ISSUER','AGENT_SCOPE_LIMITS','CONNECTOR_ENCRYPTION_KEY','CONNECTOR_KEY_PATH','CONNECTOR_ALLOWED_WOOCOMMERCE_HOSTS','SHOPIFY_CLIENT_ID','SHOPIFY_CLIENT_SECRET','SHOPIFY_PREVIOUS_CLIENT_SECRET','SHOPIFY_PREVIOUS_CLIENT_SECRET_VALID_UNTIL','SHOPIFY_REDIRECT_URI','SHOPIFY_SCOPES','SHOPIFY_WORKER_ENABLED'],
  cockpit: ['HOTL_INTERNAL_TOKEN','GUARDRAIL_SERVICE_URL','ORCHESTRATOR_URL','KILL_SWITCH_URL','KILL_SWITCH_READ_TOKEN','KILL_SWITCH_OWNER_TOKEN','NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_ANON_KEY','HOTL_PUBLIC_ORIGIN'],
  storefront: ['COMMERCE_URL','STOREFRONT_PUBLIC_ORIGIN'],
  commerce: ['HOTL_INTERNAL_TOKEN','GUARDRAIL_URL','GUARDRAIL_SERVICE_URL','REDIS_URL','STRIPE_WEBHOOK_SECRET'],
  orchestrator: ['HOTL_INTERNAL_TOKEN','GUARDRAIL_URL','GUARDRAIL_SERVICE_URL','KILL_SWITCH_URL','KILL_SWITCH_READ_TOKEN','DATABASE_URL','REDIS_URL','ENABLE_QUEUE_WORKERS','ENABLE_SCHEDULED_RUNS','ORCHESTRATOR_STATE_PATH','LITELLM_BASE_URL','LITELLM_MODEL_ALIAS','LITELLM_ORCHESTRATOR_KEY','LITELLM_SOURCING_KEY','LITELLM_MARKETING_KEY','LITELLM_ORDER_KEY','LITELLM_SUPPORT_KEY','AGENT_JWT_MASTER_ORCHESTRATOR','AGENT_JWT_SOURCING_AGENT','AGENT_JWT_MARKETING_AGENT','AGENT_JWT_ORDER_AGENT','AGENT_JWT_SUPPORT_AGENT'],
  'kill-switch': ['KILL_SWITCH_JOURNAL','KILL_SWITCH_PORT','KILL_SWITCH_READ_TOKEN','KILL_SWITCH_OWNER_TOKEN','KILL_SWITCH_DEMO_PASSWORD'],
};
export function environmentFor(service, source) {
  if (!allowed[service]) throw new Error('Unknown local service');
  const names = new Set([...common, ...allowed[service]]);
  return Object.fromEntries(Object.entries(source).filter(([name,value]) => value !== undefined && (systemKeys.has(name.toUpperCase()) || names.has(name))));
}

// An isolated browser drill must not inherit database, provider, proxy or
// remote-service settings from the developer's environment.
export function isolatedTestEnvironment(source) {
  return Object.fromEntries(Object.entries(source).filter(([name, value]) =>
    value !== undefined && systemKeys.has(name.toUpperCase()) && name.toUpperCase() !== 'NODE_ENV'));
}
